### ISSUE TITLE
Wiki LR, SRS ...

### ISSUE THREAD

**Issue by fstasel** [CankayaUniversity/ceng-407-408-2020-2021-Integrating-Digital-Queue-Line-Order-Screens-Into-Phone-Application-Express-#2]
Wiki sayfanızda literatür taraması, srs gibi istenen belgeler Literature Reivew, Software Requirements Specification gibi formal başlıklar altında olsun. Değerlendirmede problem yaşayabilirsiniz.

**Comment by COD3M4ST3R** [comment]
Istenilen belgelerin hazırlanmıs olan sayfalarının yerleri Wiki kısmına eklendi. Teşekkürler...
